Cr 1089 Test that GetCaseByUprn and GetCaseByID will choose the RM case if more recent than Cache case
ONSdigital/census-contact-centre-cucumber pull request #64
Opened 2020-09-11 10:02 UTC by cookel2

# Motivation and Context

This change is required in order to test the following scenarios:

Given the case does not exist in the cache
And the case exists in RM
When the case address details are modified
And the case modified event is sent to RM and RM <does immediately> action it
When the call is made to fetch the case again from GetCaseByUPRN
Then GetCaseByUPRN gets the modified case from RM

Given the case does not exist in the cache
And the case exists in RM
When the case address details are modified
And the case modified event is sent to RM and RM <does immediately> action it
When the call is made to fetch the case again from GetCaseByID
Then GetCaseByID gets the modified case from RM

# What has changed

The testCaseEndpoints feature file has had the following added to it:

  @CC @TestCaseEndpointsT382
  Scenario Outline: [CR-T382, CR-T384] Get latest case from RM
    Given the case with id "5a54ee1f-3552-4a46-adcc-0940f0998f90" and uprn "1710030112" does not exist in the cache
    And an empty queue exists for sending "ADDRESS_MODIFIED" events
    And the case exists in RM and can be fetched using <endpoint>
    When the case address details are modified by a member of CC staff
    And the case modified event is sent to RM and RM does immediately action it
    And the call is made to fetch the case again from <endpoint>
    Then <endpoint> gets the modified case from RM

    Examples: 
      | endpoint        |
      | "GetCaseByUPRN" |
      | "GetCaseByID"   |

The following Java classes have been amended in order to implement the T382 scenario and also to update all the relevant uprns so that there are no longer any historical ones being used in the Contact Centre acceptasnce tests:
TestCaseEndpoints
ResetMockCaseApiAndPostCasesBase

NB. These tests have passed in dev. However, they will not pass against the current master version of the mock case service. Therefore this PR must not be merged until the following PR is also ready to be merged: https://github.com/ONSdigital/census-mock-case-api-service/pull/29

# How to test?

Test the changes by running the CC Cuc acceptance tests. To run them locally follow these steps: https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=SDC&title=How+to+Run+CCCUC+Locally

2020-09-15 10:01 UTC, rpcatling requested changes

2020-09-15 10:01 UTC, rpcatling commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> +          "A HttpClientErrorException has occurred when trying to modify a case using putCaseById endpoint in contact centre: "
grammar:  A -> An

2020-09-15 10:42 UTC, cookel2 commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> +        // If no case with that id is found in Firestore then catch the exception and just log it
I can check in dev but I'm certain that it does throw an exception if it can't find a case to delete for the id in question.

2020-09-15 10:52 UTC, cookel2 commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> +  // private ResponseEntity<List<CaseDTO>> getCaseForUprn(String uprn) {
done

2020-09-15 12:23 UTC, cookel2 commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> +  public void an_empty_queue_exists_for_sending_events(String eventTypeAsString)
Good idea. In fact I had tried to something like that earlier but had failed - it was with a different method though - I think that's why I hadn't thought about it again. Thanks for pointing it out.

2020-09-15 12:28 UTC, cookel2 commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> +  public void the_case_exists_in_RM_and_can_be_fetched_using(String strEndpoint) {
That's good. I wasn't sure about the name "strEndpoint" but didn't know what else to use. Thanks for the information.

2020-09-15 12:28 UTC, cookel2 commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> +  public void the_call_is_made_to_fetch_the_case_again_from(String strEndpoint) {
done

2020-09-15 13:48 UTC, cookel2 commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> +          "A HttpClientErrorException has occurred when trying to get list of cases using getCaseByUprn endpoint in contact centre: "
done

2020-09-15 13:57 UTC, cookel2 commented on src/test/resources/integrationtests/case/testCaseEndpoints.feature
> +    Then <endpoint> gets the modified case from RM
The wording is copied from Jira. However, it's a good spot, so I will change the last step to this: Then the latest case is fetched, which is the modified case from RM

2020-09-15 15:43 UTC, cookel2 commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> +    caseContainerInRM.setCreatedDateTime(new Date());
makes sense - done

2020-09-15 15:44 UTC, cookel2 commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> +    caseContainerInRM.setAddressLine1("44 RM Road");
done

2020-09-15 15:45 UTC, cookel2 commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> +          "A HttpClientErrorException has occurred when trying to modify a case using putCaseById endpoint in contact centre: "
done

2020-09-16 14:30 UTC, cookel2 commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> +        // If no case with that id is found in Firestore then catch the exception and just log it
I've checked and you're right although it does still want me to either catch an exception or make the method signature throw one - so I've changed it to do the latter.

2020-09-16 15:26 UTC, cookel2 commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> +    caseContainerInRM.setAddressLine1("44 RM Road");
I've now given the one in the cache the same "RM Village" etc address as the one in the mock case service (aka RM) but I've kept the house number different and added a comment about that.

2020-09-17 07:16 UTC, rpcatling approved these changes

2020-09-17 11:08 UTC, PeterBochel requested changes
One question about exception handling.
Also comment in passing about excess code for loops.

2020-09-17 13:37 UTC, cookel2 commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/ResetMockCaseApiAndPostCasesBase.java
> +        log.warn("Exception thrown by mock case service - case: " + caseContainer.getId());
The exception currently gets caught in the master branch with the message "Posted duplicate cases - exception thrown by mock case service". So I changed the message for a more generic one (now that cases are amended rather than duplicated if they have the same id). However, I'm happy to just throw the error if that would be better.

2020-09-17 13:45 UTC, cookel2 commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> +  }
Good point. It was a hangover from code that I wrote for the first step of the scanario. In that step I created the cachedCaseIds List separately because I added the caseid to it (as well as the ids from the cases found by uprn).

2020-09-17 15:50 UTC, andrewjohnysons approved these changes

2020-09-18 08:50 UTC, PeterBochel commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/ResetMockCaseApiAndPostCasesBase.java
> +        log.warn("Exception thrown by mock case service - case: " + caseContainer.getId());
My concern here is that post fails but all that happens is that the code logs a warning and moves on, with no test failure to pinpoint where things actually went wrong.
Not sure what you mean by 'caught in the master branch'. Do you mean that the root exception has already been handled? Or do you mean that something which calls this code deals with the exception?

2020-09-18 09:13 UTC, PeterBochel approved these changes
LGTM

2020-09-18 09:13 UTC, merged