Upgrade dependencies and Spring
ONSdigital/census-contact-centre-cucumber pull request #67
Opened 2020-09-16 11:01 UTC by andrewjohnysons

Upgraded Cucumber dependencies
Upgraded Spring / cucumber dependencies
Removed inheritance from Spring runner
Glued Spring runner
Decoupled intermediate classes and wired as context beans CucTestContext, ResetMockCaseApiContext
renamed variables now in context
fixed some tests that were in error
Also fixed mismatched feature statements

2020-10-05 11:05 UTC, rpcatling requested changes
LGTM, just the version updates suggested. Also need to merge from master to do final check.

2020-10-07 11:10 UTC, andrewjohnysons commented on pom.xml
> +      <version>5.4.0</version>
implemented - thanks for pointing those out.

2020-10-08 12:37 UTC, rpcatling approved these changes

2020-10-09 15:07 UTC, cookel2 requested changes
Andy, I'm suggesting a change due to a recent change in the mock case service. Thanks, Ella

2020-10-09 15:07 UTC, cookel2 commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/context/ResetMockCaseApiContext.java
> +      } catch (HttpClientErrorException mockDuplicateCaseException) {
I think this try catch block needs to be removed because the mock case service doesn't complain about duplicate cases anymore - it just updates the existing case with whatever has been posted.

2020-11-19 17:48 UTC, andrewjohnysons commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/context/ResetMockCaseApiContext.java
> +      } catch (HttpClientErrorException mockDuplicateCaseException) {
resolved

2020-11-20 09:56 UTC, cookel2 approved these changes

2020-11-24 11:03 UTC, merged