Cr 1088 taken from similar 1089
ONSdigital/census-contact-centre-cucumber pull request #69
Opened 2020-09-17 11:42 UTC by andrewjohnysons

Added tests to @cookel2 story about fetching cases from RM. 
These tests do not post to RM but get updated case from cache - matching address modiciation date

2020-09-22 14:43 UTC, cookel2 reviewed
Andy, I think there might be a missing method - please see comments.

2020-09-22 14:43 UTC, cookel2 commented on src/test/resources/integrationtests/case/testCaseEndpoints.feature
> +    Then the latest case is fetched, which is the modified case from cache
It doesn't look like these's a method for the last step of this scenario (I can't find it).

2020-09-22 14:43 UTC, cookel2 commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> -    // the cache)
Please can this comment, be added to the top of this method, or something similar. It refers to the CR-382 and CR-384 tests so it's worth saying something like "The following simulates the RM data being modified but with one tiny difference (which wouldn't be there in real life) to facilitate testing of CR-382 and CR-384. The difference is in addressLine1, which is "44 RM Road" in RM but "33 RM Road" in the cache."

2020-09-22 16:07 UTC, andrewjohnysons commented on src/test/resources/integrationtests/case/testCaseEndpoints.feature
> +    Then the latest case is fetched, which is the modified case from cache
Addressed - there was but it wasn't linked for some reason....

2020-09-22 16:07 UTC, andrewjohnysons commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> -    // the cache)
I've moved the comment

2020-09-23 07:35 UTC, rpcatling requested changes
The new functionality is OK I think, but I have some comments to do with the refactoring changes, some of which have undone some of the review comment changes that Ella made for CR-1089.

2020-09-23 07:35 UTC, rpcatling commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> +      caseDTO = caseDTOList.stream().max(Comparator.comparing(CaseDTO::getCreatedDateTime)).get();
I'm not sure how much improvement this line brings, because it is a half-truth.

In the real world and the real code, the RM date/time important item is lastUpdated date/time, and the cache has createdDateTime. Whichever is newer wins.  

The trouble with this code is that it could propagate a misunderstanding of how the "latest" is determined.

2020-09-23 07:35 UTC, rpcatling commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> -    modifyCaseRequest = new ModifyCaseRequestDTO();
In moving this to ExampleData you have changed the data, which I discussed at some length with Ella in the CR-1089 PR. See other comments.

2020-09-23 07:35 UTC, rpcatling commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> +    // createCaseContainer - the difference is 44 rather than 33 (used in the cache)
You have decoupled the comments and the special reason for this code by moving it to ExampleData, so I think some understanding has been lost here.  The whole point is that in real life the RM data should have been the SAME as the modified data, with only the date/time as a differerence.

2020-09-23 07:35 UTC, rpcatling commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/data/ExampleData.java
> +    final ModifyCaseRequestDTO modifyCaseRequest = new ModifyCaseRequestDTO();
Please change this data back to how Ella had it for this method.  
For extra brownie points factor out some of the data into static variables , and reuse in the method below, so that we can see that that match up with the "createCaseContainer" method below.

2020-09-23 07:35 UTC, rpcatling commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/data/ExampleData.java
> +  public static CaseContainerDTO createCaseContainer(final String caseId, final String uprnStr) {
This is a method that simulates creating RM data that matches the modified data. So it would be better to have a more descriptive method name.  And the data should match the method above for realism , apart from the small change introduced in address line 1 , as a device to check we got it "from RM'. You have left behind a comment in the calling code, which would be helpful moving here.

2020-09-24 09:21 UTC, cookel2 approved these changes
looks good Andy

2020-09-24 12:41 UTC, rpcatling approved these changes

2020-09-24 12:41 UTC, merged