CR-1208 | updating the version for census-contact-centre-api
ONSdigital/census-contact-centre-cucumber pull request #70
Opened 2020-09-23 16:31 UTC by akritisinhaa

The EstabType has been update within the swagger yml files in census-contact-centre-service-api
Updating the version of census-contact-centre-service-api in pom.xml

For more details on the changes please have a look at https://collaborate2.ons.gov.uk/jira/browse/CR-1208.

2020-09-24 15:12 UTC, andrewjohnysons approved these changes
The requirement to populate the DTO with a UUID instead of a string means that a test has been removed - it needs to be revisited at some point

2020-09-25 09:31 UTC, rpcatling requested changes
a test scenario  accidentally removed i think

2020-09-25 09:31 UTC, rpcatling commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> -  @Given("I have an invalid case ID {string}")
By removing these steps, we impact test scenario T135. Not sure its a great test, but I don't think we should inadvertently remove it.

2020-09-25 09:33 UTC, akritisinhaa commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> -  @Given("I have an invalid case ID {string}")
This will be covered in https://collaborate2.ons.gov.uk/jira/browse/CR-1244..This issue exists because of the changes made in CR-1160 to contact centre and cucumber tests where not updated to point to the right version of contact centre api

2020-09-25 09:39 UTC, MartinHumphrey submitted a review, later dismissed
LGTM
Subsequent problems found need to be resolved.

2020-09-25 10:17 UTC, rpcatling commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> -  @Given("I have an invalid case ID {string}")
I have talked to Akriti and she has understood the issue which goes beyond her comment above. Changes will need to be made.

2020-09-25 11:15 UTC, rpcatling approved these changes

2020-09-25 11:15 UTC, merged