Cr 1116
ONSdigital/census-contact-centre-cucumber pull request #79
Opened 2021-01-12 09:39 UTC by Raysonviswas

Fixed a Bunch of pending tests in testFulfilmentsEndpoint.feature and deleted ones that aren't required any more.

added Test CR-T412

2021-01-13 09:02 UTC, andrewjohnysons commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> +      System.exit(0);
Not comfortable about System exits other than in smoke tests. 
The test will fail, which is enough

2021-01-13 09:06 UTC, andrewjohnysons commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> +  public void cc_advisor_receives_error(String msg) {}
Why?
What's the point in having this method if it doesn't do anything?

2021-01-13 09:10 UTC, andrewjohnysons commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/fulfilments/TestFulfilmentsEndpoints.java
> +    String fulfilmentCode = event.getPayload().getFulfilmentRequest().getFulfilmentCode();
This block won't work - you need to use the .equals() method.....

    String fulfilmentCode = event.getPayload().getFulfilmentRequest().getFulfilmentCode();
    if (addressType.equals("HH") && individual.equals("false")) {
      assertEquals("P_UAC_UACHHP4", fulfilmentCode);
    } else if (addressType.equals("HH") && individual.equals("true")) {
      assertEquals("P_UAC_UACIP2B", fulfilmentCode);
    } else if (addressType.equals("CE") && individual.equals("true")) {
      assertEquals("P_UAC_UACIP2B", fulfilmentCode);
    } else if (addressType.equals("SPG") && individual.equals("false")) {
      assertEquals("P_UAC_UACIP2B", fulfilmentCode);
    } else if (addressType.equals("CE") && individual.equals("false")) {
      assertEquals("P_UAC_UACIP2B", fulfilmentCode);
    }

2021-01-13 09:11 UTC, andrewjohnysons commented on src/test/resources/integrationtests/case/testTelephoneEndpoint.feature
> +    Then CC advisor receives error <caseId> <message> <individual>
Better to use "And" here

2021-01-13 09:12 UTC, andrewjohnysons requested changes
Couple of bits and pieces but nothing major

2021-01-18 10:23 UTC, rpcatling requested changes
I don't feel like I can review this until it is clear what has been changed and why.
Please:
- elaborate on what has been agreed and changed in the JIRA  and PR description
- reply in the github review comments to Andy's comments to say if they are done or not

2021-01-19 09:26 UTC, Raysonviswas commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> +      System.exit(0);
taken out

2021-01-19 09:26 UTC, Raysonviswas commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> +  public void cc_advisor_receives_error(String msg) {}
taken out

2021-01-19 09:27 UTC, Raysonviswas commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/fulfilments/TestFulfilmentsEndpoints.java
> +    String fulfilmentCode = event.getPayload().getFulfilmentRequest().getFulfilmentCode();
replaced block with individual fulfilment codes that get passed in

2021-01-19 09:29 UTC, Raysonviswas commented on src/test/resources/integrationtests/case/testTelephoneEndpoint.feature
> +    Then CC advisor receives error <caseId> <message> <individual>
"Then" currently used by other tests will do a work around

2021-01-20 09:23 UTC, Raysonviswas commented on src/test/resources/integrationtests/case/testTelephoneEndpoint.feature
> +    Then CC advisor receives error <caseId> <message> <individual>
Changed Then to an And, seems to work fine

2021-01-22 09:23 UTC, andrewjohnysons commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/fulfilments/TestFulfilmentsEndpoints.java
> +    String fulfilmentCode = event.getPayload().getFulfilmentRequest().getFulfilmentCode();
better

2021-01-22 09:24 UTC, andrewjohnysons approved these changes

2021-01-22 11:00 UTC, rpcatling requested changes
A few comments, in particular I cannot determine if it was right to remove the tests you did. Please update the JIRA with information from Ameet to confirm the deletions.

Also make sure you merge from master.

2021-01-25 08:50 UTC, Raysonviswas commented on src/test/resources/integrationtests/fulfilments/testFulfilmentsEndpoint.feature
> -  Scenario Outline: [CR-T269, CR-T273, CR-T293, CR-T306, CR-T319, CR-T322] PENDING - I want to request a Paper Questionnaire for SMS delivery channel
[CR-T269, CR-T273, CR-T293, CR-T306, CR-T319, CR-T322] PENDING - I want to request a Paper Questionnaire for SMS delivery channel

was merged with 

Scenario Outline: [CR-T269, CR-T273, CR-T293, CR-T306, CR-T319, CR-T322] I want to request a individual for SMS delivery channel

2021-01-28 09:33 UTC, Raysonviswas commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/cases/TestCaseEndpoints.java
> +  public void cc_advisor_recieves(final String caseId, final String errMsg, final String individual)
spelling changed implemented cc_advisor_receives_error suggestion

2021-01-28 09:34 UTC, Raysonviswas commented on src/test/resources/integrationtests/case/testTelephoneEndpoint.feature
> +  Scenario Outline: CR-T412 - NI CE manager recieves an error on EQ launch
changed spelling

2021-01-28 09:36 UTC, Raysonviswas commented on src/test/resources/integrationtests/case/testTelephoneEndpoint.feature
> +    Given I have a valid UPRN "1347459997"
@TeleEndpoint-CR-T412 allows you to run the test in isolation,
 the Given step just uses existing code to check validity of UPRN

2021-01-28 09:36 UTC, Raysonviswas commented on src/test/resources/integrationtests/fulfilments/testFulfilmentsEndpoint.feature
> +    Then a fulfilment request event is emitted to RM with expected fulfilemnt code = "P_UAC_UACHHP4"
fixed in all places in the file

2021-01-28 09:36 UTC, Raysonviswas commented on src/test/java/uk/gov/ons/ctp/integration/contcencucumber/cucSteps/fulfilments/TestFulfilmentsEndpoints.java
> +  @Then("a fulfilment request event is emitted to RM with expected fulfilemnt code = {string}")
fixed in all places in the file

2021-01-28 09:37 UTC, Raysonviswas commented on src/test/resources/integrationtests/fulfilments/testFulfilmentsEndpoint.feature
> -  Scenario Outline: [CR-T375] I want to check that EMPTY title, forename or surname items are not fulfilled for an individual POSTAL request
should now be working - reimplemented and updated for my requirements
Title no longer required

2021-01-28 11:56 UTC, rpcatling commented on src/test/resources/integrationtests/case/testTelephoneEndpoint.feature
> +    Given I have a valid UPRN "1347459997"
As described in our slack conversation, I think this could be much better

2021-01-29 11:21 UTC, Raysonviswas commented on src/test/resources/integrationtests/fulfilments/testFulfilmentsEndpoint.feature
> -  @SetUp
done

2021-01-29 11:21 UTC, Raysonviswas commented on src/test/resources/integrationtests/fulfilments/testFulfilmentsEndpoint.feature
> -  Scenario: [CR-T323] PENDING - I want to request a Paper Questionnaire for a SPG Individual Respondent in NI
done

2021-01-29 11:23 UTC, Raysonviswas commented on src/test/resources/integrationtests/case/testTelephoneEndpoint.feature
> +    Given I have a valid UPRN "1347459997"
Refactored the Scenario as suggested by Rob

2021-01-29 15:38 UTC, rpcatling approved these changes

2021-01-29 15:39 UTC, merged